### ISSUE TITLE
请问branch，这个部署分支变量要放在哪里？

### ISSUE THREAD

**Issue by SaulJWu** [yanglbme/gitee-pages-action#23]
我的ci文件如下
~~~yml
name: GiteeSync

on:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:SaulJWu/SaulJWu.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:SaulJWu/SaulJWu.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: SaulJWu
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: SaulJWu/SaulJWu

~~~

如果branches默认是master，是会触发工作流程的，但是我每次都要去gitee pages设置部署分支
但是改了branches为gh-pages后，就不触发工作流程了。

参考您的文档：https://github.com/marketplace/actions/gitee-pages-action

要部署的分支应该是branch，而不是on.push.branches，这个是触发工作流程条件
那么部署分支是写在下面吗？
例如：
~~~yml
 - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: SaulJWu
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: SaulJWu/SaulJWu
          # 要部署的分支
          branch: gh-pages
~~~
是这样子写吗?还是怎么写，刚刚接触git actions= =还望多多指导一下我

**Comment by yanglbme** [comment]
嗯，是这样写。

```yml
# 注意替换为你的 Gitee 用户名
gitee-username: SaulJWu
# 注意在 Settings->Secrets 配置 GITEE_PASSWORD
gitee-password: ${{ secrets.GITEE_PASSWORD }}
# 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
gitee-repo: SaulJWu/SaulJWu
# 要部署的分支
branch: gh-pages
```

**Comment by yanglbme** [comment]
顶部 on push 只是触发 action 执行而已。

比如你那样配置，就是当 GitHub push 到 gh-pages 分支时，触发下面的 jobs 执行。

**Comment by SaulJWu** [comment]
> 顶部 on push 只是触发 action 执行而已。
> 
> 比如你那样配置，就是当 GitHub push 到 gh-pages 分支时，触发下面的 jobs 执行。

明白了，现在已经成功了，但是我发现一个小问题，giteeSync会慢一个版本。
我有两个action，
第一个是部署到github的action，我称为githubCI吧
第二个是同步到gitee的action，称为giteeSync吧。
问题来了
每当我写完文档后，push的时候，两个action都会同时执行，
但是giteeSync会比githubCI的快，此时giteeSync已经完成了，
但是githubCI还在编译中（我clone了别人的主题，每次都要build几分钟），后面才完成，才部署到github中。

也就说giteeSync会把上次在github部署好的同步到gitee中，而然后面githubCI重新部署到github的代码并没有同步到gitee中，从而导致gitee比github慢一个版本。

~~~yml
name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run deploy.sh # 步骤3 （同时部署到github和coding）
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          # CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
        run: npm install && npm run deploy
      - name: Build and Deploy # 步骤3 （只提交到github可以使用这个步骤）
        uses: JamesIves/github-pages-deploy-action@master # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
        env: # 设置环境变量
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          BASE_BRANCH: master # 要部署的文件夹所在的分支.
          BRANCH: gh-pages # 部署到的分支
          FOLDER: docs/.vuepress/dist # 要部署的文件夹.
          BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist  && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）
~~~

~~~yml
name: GiteeSync

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:SaulJWu/SaulJWu.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:SaulJWu/SaulJWu.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: SaulJWu
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: SaulJWu/SaulJWu
          # 要部署的分支
          branch: gh-pages
~~~

如果想让giteeSync也等githubCI完成，具体要怎么做呢？
ACTION有没有定时任务，比如10分钟后才进行？
还是拷贝githubCI.yml某个步骤到giteeSync.yml当中？

**Comment by yanglbme** [comment]
我看了你最新的配置，还是有问题，流程的先后顺序不对。

应该改为如下，也即是 on push 的 branches 也是 [gh-pages]

```yml
name: GiteeSync

on:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:SaulJWu/SaulJWu.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:SaulJWu/SaulJWu.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: SaulJWu
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: SaulJWu/SaulJWu
          # 要部署的分支
          branch: gh-pages
```

**Comment by yanglbme** [comment]
你的 ci 执行成功，就会 push 到 github 的 gh-pages 分支，此时便会触发 giteeSync，将最新的代码同步至 gitee 并自动部署。

**Comment by SaulJWu** [comment]
> 你的 ci 执行成功，就会 push 到 github 的 gh-pages 分支，此时便会触发 giteeSync，将最新的代码同步至 gitee 并自动部署。

明白了，是我搞混了，以为是同步执行= =，感谢

**Comment by yanglbme** [comment]
应该没问题了吧，刷新 gitee 的 pages 站点，应该可以看到最新的。

**Comment by SaulJWu** [comment]
> 应该没问题了吧，刷新 gitee 的 pages 站点，应该可以看到最新的。

好像没有触发giteeSync，是不是因为我的CI都是强制推送啊？

**Comment by yanglbme** [comment]
会触发的，只是如果不是默认分支，GitHub 不会把 workflow 的运行输出到界面。所以就看似没触发。我的开源项目 https://github.com/doocs/md/tree/gh-pages 也是这样，但到 gitee pages，可以看到最新的代码效果。

**Comment by yanglbme** [comment]
你也可以改成 on page_build，这样就是 github pages 构建完毕后触发。

```yml
name: GiteeSync

on:
  page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:SaulJWu/SaulJWu.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:SaulJWu/SaulJWu.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: SaulJWu
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: SaulJWu/SaulJWu
          # 要部署的分支
          branch: gh-pages
```
