### ISSUE TITLE
请问直接使用Build Gitee Pages，可以吗？

### ISSUE THREAD

**Issue by claa** [yanglbme/gitee-pages-action#25]
不使用Sync to Gitee ，直接使用Build Gitee Pages的。
情景是：我的Gitee Pages 之前已经是开启的，新增了一些文件，想自动更新一下Gitee Pages，可以使用Build Gitee Pages吗？

**Comment by yanglbme** [comment]
那你是自己 push 到 gitee 仓库吗？

**Comment by yanglbme** [comment]
如果文件已经在 gitee，那么就不需要用 `wearerequired/git-mirror-action@master` 进行文件同步了，可以直接使用 `yanglbme/gitee-pages-action@main` 更新 Gitee Pages。配置文件大致如下，on 触发条件以及账号、仓库信息可以自行配置。

```yml
name: Sync

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: yanglbme
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: doocs/advanced-java
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: main
```

**Comment by claa** [comment]
```
name: CI

# 在master分支发生push事件时触发。
on: 
  push:
    branches:
      - main
jobs: # 工作流
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps: 
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run deploy.sh # 步骤3 （同时部署到github和coding）
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        run: npm install && npm run deploy # 执行的命令  
        # package.json 中添加 "deploy": "bash deploy.sh"
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: claa
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: vuepress-theme-vdoing
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: master
```

就是到Build Gitee Pages 这步失败，github action 日志中也没有提示显示错误原因，用户名和密码是正确的。我想直接从github action 上自动更新gitee pages 服务，是这有问题吗？
